"""initial migration

Revision ID: d056c4856691
Revises: 
Create Date: 2025-11-05 00:43:42.365535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd056c4856691'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('Dept_ID', sa.Integer(), nullable=False),
    sa.Column('Dept_Head', sa.String(length=20), nullable=False),
    sa.Column('Dept_Name', sa.String(length=15), nullable=False),
    sa.Column('Emp_Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Dept_ID')
    )
    op.create_index(op.f('ix_Department_Dept_ID'), 'Department', ['Dept_ID'], unique=False)
    op.create_table('Medicine',
    sa.Column('Medicine_ID', sa.Integer(), nullable=False),
    sa.Column('M_Name', sa.String(length=20), nullable=False),
    sa.Column('M_Quantity', sa.Integer(), nullable=False),
    sa.Column('M_Cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('Medicine_ID')
    )
    op.create_index(op.f('ix_Medicine_Medicine_ID'), 'Medicine', ['Medicine_ID'], unique=False)
    op.create_table('Patient',
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Patient_FName', sa.String(length=20), nullable=False),
    sa.Column('Patient_LName', sa.String(length=20), nullable=False),
    sa.Column('Phone', sa.String(length=12), nullable=False),
    sa.Column('Blood_Type', sa.String(length=5), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('Condition_', sa.String(length=30), nullable=True),
    sa.Column('Admission_Date', sa.Date(), nullable=True),
    sa.Column('Discharge_Date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Patient_ID')
    )
    op.create_index(op.f('ix_Patient_Patient_ID'), 'Patient', ['Patient_ID'], unique=False)
    op.create_table('Emergency_Contact',
    sa.Column('Contact_ID', sa.Integer(), nullable=False),
    sa.Column('Contact_Name', sa.String(length=20), nullable=False),
    sa.Column('Phone', sa.String(length=12), nullable=False),
    sa.Column('Relation', sa.String(length=20), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.PrimaryKeyConstraint('Contact_ID')
    )
    op.create_index(op.f('ix_Emergency_Contact_Contact_ID'), 'Emergency_Contact', ['Contact_ID'], unique=False)
    op.create_table('Insurance',
    sa.Column('Policy_Number', sa.String(length=20), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Ins_Code', sa.String(length=20), nullable=False),
    sa.Column('End_Date', sa.String(length=10), nullable=True),
    sa.Column('Provider', sa.String(length=20), nullable=True),
    sa.Column('Plan', sa.String(length=20), nullable=True),
    sa.Column('Co_Pay', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Coverage', sa.String(length=20), nullable=True),
    sa.Column('Maternity', sa.Boolean(), nullable=True),
    sa.Column('Dental', sa.Boolean(), nullable=True),
    sa.Column('Optical', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.PrimaryKeyConstraint('Policy_Number')
    )
    op.create_index(op.f('ix_Insurance_Policy_Number'), 'Insurance', ['Policy_Number'], unique=False)
    op.create_table('Medical_History',
    sa.Column('Record_ID', sa.Integer(), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Allergies', sa.String(length=50), nullable=True),
    sa.Column('Pre_Conditions', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.PrimaryKeyConstraint('Record_ID')
    )
    op.create_index(op.f('ix_Medical_History_Record_ID'), 'Medical_History', ['Record_ID'], unique=False)
    op.create_table('Room',
    sa.Column('Room_ID', sa.Integer(), nullable=False),
    sa.Column('Room_Type', sa.String(length=50), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Room_Cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.PrimaryKeyConstraint('Room_ID')
    )
    op.create_index(op.f('ix_Room_Room_ID'), 'Room', ['Room_ID'], unique=False)
    op.create_table('Staff',
    sa.Column('Emp_ID', sa.Integer(), nullable=False),
    sa.Column('Emp_FName', sa.String(length=20), nullable=False),
    sa.Column('Emp_LName', sa.String(length=20), nullable=False),
    sa.Column('Date_Joining', sa.Date(), nullable=True),
    sa.Column('Date_Seperation', sa.Date(), nullable=True),
    sa.Column('Emp_Type', sa.String(length=15), nullable=False),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('Address', sa.String(length=50), nullable=False),
    sa.Column('Dept_ID', sa.Integer(), nullable=False),
    sa.Column('SSN', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Dept_ID'], ['Department.Dept_ID'], ),
    sa.PrimaryKeyConstraint('Emp_ID')
    )
    op.create_index(op.f('ix_Staff_Emp_ID'), 'Staff', ['Emp_ID'], unique=False)
    op.create_table('Bill',
    sa.Column('Bill_ID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Room_Cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Test_Cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Other_Charges', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('M_Cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Remaining_Balance', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Policy_Number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.ForeignKeyConstraint(['Policy_Number'], ['Insurance.Policy_Number'], ),
    sa.PrimaryKeyConstraint('Bill_ID')
    )
    op.create_index(op.f('ix_Bill_Bill_ID'), 'Bill', ['Bill_ID'], unique=False)
    op.create_table('Doctor',
    sa.Column('Doctor_ID', sa.Integer(), nullable=False),
    sa.Column('Qualifications', sa.String(length=15), nullable=False),
    sa.Column('Emp_ID', sa.Integer(), nullable=False),
    sa.Column('Specialization', sa.String(length=20), nullable=False),
    sa.Column('Dept_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Dept_ID'], ['Department.Dept_ID'], ),
    sa.ForeignKeyConstraint(['Emp_ID'], ['Staff.Emp_ID'], ),
    sa.PrimaryKeyConstraint('Doctor_ID')
    )
    op.create_index(op.f('ix_Doctor_Doctor_ID'), 'Doctor', ['Doctor_ID'], unique=False)
    op.create_table('Nurse',
    sa.Column('Nurse_ID', sa.Integer(), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Emp_ID', sa.Integer(), nullable=False),
    sa.Column('Dept_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Dept_ID'], ['Department.Dept_ID'], ),
    sa.ForeignKeyConstraint(['Emp_ID'], ['Staff.Emp_ID'], ),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.PrimaryKeyConstraint('Nurse_ID')
    )
    op.create_index(op.f('ix_Nurse_Nurse_ID'), 'Nurse', ['Nurse_ID'], unique=False)
    op.create_table('Payroll',
    sa.Column('Account_No', sa.String(length=25), nullable=False),
    sa.Column('Salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('Bonus', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Emp_ID', sa.Integer(), nullable=False),
    sa.Column('IBAN', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['Emp_ID'], ['Staff.Emp_ID'], ),
    sa.PrimaryKeyConstraint('Account_No')
    )
    op.create_index(op.f('ix_Payroll_Account_No'), 'Payroll', ['Account_No'], unique=False)
    op.create_table('Appointment',
    sa.Column('Appt_ID', sa.Integer(), nullable=False),
    sa.Column('Scheduled_On', sa.DateTime(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Time', sa.Time(), nullable=True),
    sa.Column('Doctor_ID', sa.Integer(), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Doctor_ID'], ['Doctor.Doctor_ID'], ),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.PrimaryKeyConstraint('Appt_ID')
    )
    op.create_index(op.f('ix_Appointment_Appt_ID'), 'Appointment', ['Appt_ID'], unique=False)
    op.create_table('Lab_Screening',
    sa.Column('Lab_ID', sa.Integer(), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Technician_ID', sa.Integer(), nullable=False),
    sa.Column('Doctor_ID', sa.Integer(), nullable=False),
    sa.Column('Test_Cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['Doctor_ID'], ['Doctor.Doctor_ID'], ),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.ForeignKeyConstraint(['Technician_ID'], ['Staff.Emp_ID'], ),
    sa.PrimaryKeyConstraint('Lab_ID')
    )
    op.create_index(op.f('ix_Lab_Screening_Lab_ID'), 'Lab_Screening', ['Lab_ID'], unique=False)
    op.create_table('Prescription',
    sa.Column('Prescription_ID', sa.Integer(), nullable=False),
    sa.Column('Patient_ID', sa.Integer(), nullable=False),
    sa.Column('Medicine_ID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Dosage', sa.Integer(), nullable=True),
    sa.Column('Doctor_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Doctor_ID'], ['Doctor.Doctor_ID'], ),
    sa.ForeignKeyConstraint(['Medicine_ID'], ['Medicine.Medicine_ID'], ),
    sa.ForeignKeyConstraint(['Patient_ID'], ['Patient.Patient_ID'], ),
    sa.PrimaryKeyConstraint('Prescription_ID')
    )
    op.create_index(op.f('ix_Prescription_Prescription_ID'), 'Prescription', ['Prescription_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Prescription_Prescription_ID'), table_name='Prescription')
    op.drop_table('Prescription')
    op.drop_index(op.f('ix_Lab_Screening_Lab_ID'), table_name='Lab_Screening')
    op.drop_table('Lab_Screening')
    op.drop_index(op.f('ix_Appointment_Appt_ID'), table_name='Appointment')
    op.drop_table('Appointment')
    op.drop_index(op.f('ix_Payroll_Account_No'), table_name='Payroll')
    op.drop_table('Payroll')
    op.drop_index(op.f('ix_Nurse_Nurse_ID'), table_name='Nurse')
    op.drop_table('Nurse')
    op.drop_index(op.f('ix_Doctor_Doctor_ID'), table_name='Doctor')
    op.drop_table('Doctor')
    op.drop_index(op.f('ix_Bill_Bill_ID'), table_name='Bill')
    op.drop_table('Bill')
    op.drop_index(op.f('ix_Staff_Emp_ID'), table_name='Staff')
    op.drop_table('Staff')
    op.drop_index(op.f('ix_Room_Room_ID'), table_name='Room')
    op.drop_table('Room')
    op.drop_index(op.f('ix_Medical_History_Record_ID'), table_name='Medical_History')
    op.drop_table('Medical_History')
    op.drop_index(op.f('ix_Insurance_Policy_Number'), table_name='Insurance')
    op.drop_table('Insurance')
    op.drop_index(op.f('ix_Emergency_Contact_Contact_ID'), table_name='Emergency_Contact')
    op.drop_table('Emergency_Contact')
    op.drop_index(op.f('ix_Patient_Patient_ID'), table_name='Patient')
    op.drop_table('Patient')
    op.drop_index(op.f('ix_Medicine_Medicine_ID'), table_name='Medicine')
    op.drop_table('Medicine')
    op.drop_index(op.f('ix_Department_Dept_ID'), table_name='Department')
    op.drop_table('Department')
    # ### end Alembic commands ###
